services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: conexaoestagios
    ports:
      - "8081:8080"
    environment:
      POSTGRES_URL: ${POSTGRES_URL}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_PROFILES_ACTIVE: dev
    depends_on:
    - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: 2704
      POSTGRES_DB: conexaoestagios
